name: CI/CD pipeline
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Describe environment
        run: docker --version && docker-compose --version
      - name: Test rdbms container
        working-directory: ${{ github.workspace }}/rdbms
        run: timeout --preserve-status 5m docker-compose up --abort-on-container-exit
      - name: Test webserver container
        working-directory: ${{ github.workspace }}/rdbms
        run: timeout --preserve-status 5m docker-compose up --abort-on-container-exit
