name: CI/CD pipeline
on: [push]

jobs:
  test_containers:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Describe environment
        run: docker --version && docker-compose --version
      - name: Test rdbms container
        working-directory: ${{ github.workspace }}/rdbms
        run: timeout --preserve-status 2m docker-compose up --abort-on-container-exit
      - name: Test webserver container
        working-directory: ${{ github.workspace }}/webserver
        run: timeout --preserve-status 5m docker-compose up --abort-on-container-exit
